### ISSUE TITLE
Build of the image on ocp 3.11 is failing

### ISSUE THREAD

**Issue by cmoulliard** [rhoar-ci/jenkins-slave-jjb#1]
## Issue

```

Cloning "https://github.com/rhoar-ci/jenkins-agent-jjb " ...
--
  | Commit:	da8aab42c221ae7e87afd59b508574d31ece1320 (update Jenkins Job Builder)
  | Author:	Ladislav Thon <lthon@redhat.com>
  | Date:	Mon Jul 9 14:55:57 2018 +0200
  |  
  | Pulling image openshift/jenkins-slave-base-centos7:latest ...
  | Pulled 2/7 layers, 29% complete
  | Pulled 3/7 layers, 48% complete
  | Pulled 4/7 layers, 57% complete
  | Pulled 5/7 layers, 71% complete
  | Pulled 6/7 layers, 91% complete
  | Pulled 7/7 layers, 100% complete
  | Extracting
  | Step 1/10 : FROM openshift/jenkins-slave-base-centos7:latest
  | ---> 2bb57eb15e7a
  | Step 2/10 : MAINTAINER Ladislav Thon <lthon@redhat.com>
  | ---> Running in fe83cb5c65ad
  | ---> e0b1245a4ba5
  | Removing intermediate container fe83cb5c65ad
  | Step 3/10 : USER root
  | ---> Running in b90054cb2c2f
  | ---> 745c9803f1d2
  | Removing intermediate container b90054cb2c2f
  | Step 4/10 : COPY patches /tmp/patches/
  | ---> 3e15fd4d8393
  | Removing intermediate container fd7936009f3e
  | Step 5/10 : RUN yum -y install epel-release &&     yum -y install jq xmlstarlet patch python-pip &&     yum -y clean all &&     rm -rf /var/cache/yum &&     pip install --upgrade pip six 'python-jenkins==0.4.15' 'jenkins-job-builder==2.0.10' &&     for P in /tmp/patches/*.patch ; do patch --directory / --strip 0 < $P ; done &&     rm -rf /tmp/patches
  | ---> Running in befb9f9ea6c3
  |  
  | Loaded plugins: fastestmirror, ovl
  | Determining fastest mirrors
  | * base: mirror.atlanticmetro.net
  | * extras: mirror.cs.vt.edu
  | * updates: mirror.trouble-free.net
  | Resolving Dependencies
  | --> Running transaction check
  | ---> Package epel-release.noarch 0:7-11 will be installed
  | --> Finished Dependency Resolution
  |  
  | Dependencies Resolved
  |  
  | ================================================================================
  | Package                Arch             Version         Repository        Size
  | ================================================================================
  | Installing:
  | epel-release           noarch           7-11            extras            15 k
  |  
  | Transaction Summary
  | ================================================================================
  | Install  1 Package
  |  
  | Total download size: 15 k
  | Installed size: 24 k
  | Downloading packages:
  | Running transaction check
  | Running transaction test
  | Transaction test succeeded
  | Running transaction
  | Installing : epel-release-7-11.noarch                                     1/1
  | Verifying  : epel-release-7-11.noarch                                     1/1
  |  
  | Installed:
  | epel-release.noarch 0:7-11
  |  
  | Complete!
  | Loaded plugins: fastestmirror, ovl
  | Loading mirror speeds from cached hostfile
  | * base: mirror.atlanticmetro.net
  | * epel: mirror.math.princeton.edu
  | * extras: mirror.cs.vt.edu
  | * updates: mirror.trouble-free.net
  | Resolving Dependencies
  | --> Running transaction check
  | ---> Package jq.x86_64 0:1.6-2.el7 will be installed
  | --> Processing Dependency: libonig.so.5()(64bit) for package: jq-1.6-2.el7.x86_64
  | ---> Package patch.x86_64 0:2.7.1-12.el7_7 will be installed
  | ---> Package python2-pip.noarch 0:8.1.2-14.el7 will be installed
  | --> Processing Dependency: python-setuptools for package: python2-pip-8.1.2-14.el7.noarch
  | ---> Package xmlstarlet.x86_64 0:1.6.1-1.el7 will be installed
  | --> Running transaction check
  | ---> Package oniguruma.x86_64 0:6.8.2-1.el7 will be installed
  | ---> Package python-setuptools.noarch 0:0.9.8-7.el7 will be installed
  | --> Processing Dependency: python-backports-ssl_match_hostname for package: python-setuptools-0.9.8-7.el7.noarch
  | --> Running transaction check
  | ---> Package python-backports-ssl_match_hostname.noarch 0:3.5.0.1-1.el7 will be installed
  | --> Processing Dependency: python-ipaddress for package: python-backports-ssl_match_hostname-3.5.0.1-1.el7.noarch
  | --> Processing Dependency: python-backports for package: python-backports-ssl_match_hostname-3.5.0.1-1.el7.noarch
  | --> Running transaction check
  | ---> Package python-backports.x86_64 0:1.0-8.el7 will be installed
  | ---> Package python-ipaddress.noarch 0:1.0.16-2.el7 will be installed
  | --> Finished Dependency Resolution
  |  
  | Dependencies Resolved
  |  
  | ================================================================================
  | Package                               Arch     Version            Repository
  | Size
  | ================================================================================
  | Installing:
  | jq                                    x86_64   1.6-2.el7          epel   167 k
  | patch                                 x86_64   2.7.1-12.el7_7     base   111 k
  | python2-pip                           noarch   8.1.2-14.el7       epel   1.7 M
  | xmlstarlet                            x86_64   1.6.1-1.el7        epel    62 k
  | Installing for dependencies:
  | oniguruma                             x86_64   6.8.2-1.el7        epel   181 k
  | python-backports                      x86_64   1.0-8.el7          base   5.8 k
  | python-backports-ssl_match_hostname   noarch   3.5.0.1-1.el7      base    13 k
  | python-ipaddress                      noarch   1.0.16-2.el7       base    34 k
  | python-setuptools                     noarch   0.9.8-7.el7        base   397 k
  |  
  | Transaction Summary
  | ================================================================================
  | Install  4 Packages (+5 Dependent packages)
  |  
  | Total download size: 2.6 M
  | Installed size: 11 M
  | Downloading packages:
  | warning: /var/cache/yum/x86_64/7/epel/packages/jq-1.6-2.el7.x86_64.rpm: Header V3 RSA/SHA256 Signature, key ID 352c64e5: NOKEY
  | Public key for jq-1.6-2.el7.x86_64.rpm is not installed
  | --------------------------------------------------------------------------------
  | Total                                              2.5 MB/s \| 2.6 MB  00:01
  | Retrieving key from file:///etc/pki/rpm-gpg/RPM-GPG-KEY-EPEL-7
  | Importing GPG key 0x352C64E5:
  | Userid     : "Fedora EPEL (7) <epel@fedoraproject.org>"
  | Fingerprint: 91e9 7d7c 4a5e 96f1 7f3e 888f 6a2f aea2 352c 64e5
  | Package    : epel-release-7-11.noarch (@extras)
  | From       : /etc/pki/rpm-gpg/RPM-GPG-KEY-EPEL-7
  | Running transaction check
  | Running transaction test
  | Transaction test succeeded
  | Running transaction
  | Installing : oniguruma-6.8.2-1.el7.x86_64                                 1/9
  | Installing : python-ipaddress-1.0.16-2.el7.noarch                         2/9
  | Installing : python-backports-1.0-8.el7.x86_64                            3/9
  | Installing : python-backports-ssl_match_hostname-3.5.0.1-1.el7.noarch     4/9
  | Installing : python-setuptools-0.9.8-7.el7.noarch                         5/9
  | Installing : python2-pip-8.1.2-14.el7.noarch                              6/9
  | Installing : jq-1.6-2.el7.x86_64                                          7/9
  | Installing : xmlstarlet-1.6.1-1.el7.x86_64                                8/9
  | Installing : patch-2.7.1-12.el7_7.x86_64                                  9/9
  | Verifying  : patch-2.7.1-12.el7_7.x86_64                                  1/9
  | Verifying  : python-backports-ssl_match_hostname-3.5.0.1-1.el7.noarch     2/9
  | Verifying  : xmlstarlet-1.6.1-1.el7.x86_64                                3/9
  | Verifying  : python2-pip-8.1.2-14.el7.noarch                              4/9
  | Verifying  : python-backports-1.0-8.el7.x86_64                            5/9
  | Verifying  : python-ipaddress-1.0.16-2.el7.noarch                         6/9
  | Verifying  : jq-1.6-2.el7.x86_64                                          7/9
  | Verifying  : python-setuptools-0.9.8-7.el7.noarch                         8/9
  | Verifying  : oniguruma-6.8.2-1.el7.x86_64                                 9/9
  |  
  | Installed:
  | jq.x86_64 0:1.6-2.el7                   patch.x86_64 0:2.7.1-12.el7_7
  | python2-pip.noarch 0:8.1.2-14.el7       xmlstarlet.x86_64 0:1.6.1-1.el7
  |  
  | Dependency Installed:
  | oniguruma.x86_64 0:6.8.2-1.el7
  | python-backports.x86_64 0:1.0-8.el7
  | python-backports-ssl_match_hostname.noarch 0:3.5.0.1-1.el7
  | python-ipaddress.noarch 0:1.0.16-2.el7
  | python-setuptools.noarch 0:0.9.8-7.el7
  |  
  | Complete!
  | Loaded plugins: fastestmirror, ovl
  | Cleaning repos: base cbs-paas7-openshift-multiarch-el7-build centos-sclo-rh epel
  | : extras updates
  | Cleaning up everything
  | Maybe you want: rm -rf /var/cache/yum, to also free up space taken by orphaned data from disabled or removed repos
  | Cleaning up list of fastest mirrors
  | The directory '/home/jenkins/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
  | The directory '/home/jenkins/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
  | Collecting pip
  | Downloading https://files.pythonhosted.org/packages/ab/11/2dc62c5263d9eb322f2f028f7b56cd9d096bb8988fcf82d65fa2e4057afe/pip-20.3.1-py2.py3-none-any.whl  (1.5MB)
  | Collecting six
  | Downloading https://files.pythonhosted.org/packages/ee/ff/48bde5c0f013094d729fe4b0316ba2a24774b3ff1c52d924a8a4cb04078a/six-1.15.0-py2.py3-none-any.whl
  | Collecting python-jenkins==0.4.15
  | Downloading https://files.pythonhosted.org/packages/85/ca/b0f84112727c5223c78042723d1489964e18b4c90d72e7e84c8e703d2e6d/python_jenkins-0.4.15-py2-none-any.whl
  | Collecting jenkins-job-builder==2.0.10
  | Downloading https://files.pythonhosted.org/packages/4d/09/071a3ce6118d35e803ddcc1cd33b31dc0c4e177bd17d346ff91b1ab2ea92/jenkins_job_builder-2.0.10-py2.py3-none-any.whl  (284kB)
  | Collecting pbr>=0.8.2 (from python-jenkins==0.4.15)
  | Downloading https://files.pythonhosted.org/packages/fb/48/69046506f6ac61c1eaa9a0d42d22d54673b69e176d30ca98e3f61513e980/pbr-5.5.1-py2.py3-none-any.whl  (106kB)
  | Collecting multi-key-dict (from python-jenkins==0.4.15)
  | Downloading https://files.pythonhosted.org/packages/6d/97/2e9c47ca1bbde6f09cb18feb887d5102e8eacd82fbc397c77b221f27a2ab/multi_key_dict-2.0.3.tar.gz
  | Collecting PyYAML>=3.10.0 (from jenkins-job-builder==2.0.10)
  | Downloading https://files.pythonhosted.org/packages/64/c2/b80047c7ac2478f9501676c988a5411ed5572f35d1beff9cae07d321512c/PyYAML-5.3.1.tar.gz  (269kB)
  | Collecting Jinja2 (from jenkins-job-builder==2.0.10)
  | Downloading https://files.pythonhosted.org/packages/30/9e/f663a2aa66a09d838042ae1a2c5659828bb9b41ea3a6efa20a20fd92b121/Jinja2-2.11.2-py2.py3-none-any.whl  (125kB)
  | Collecting fasteners (from jenkins-job-builder==2.0.10)
  | Downloading https://files.pythonhosted.org/packages/18/bd/55eb2d6397b9c0e263af9d091ebdb756b15756029b3cededf6461481bc63/fasteners-0.15-py2.py3-none-any.whl
  | Collecting stevedore>=1.17.1 (from jenkins-job-builder==2.0.10)
  | Downloading https://files.pythonhosted.org/packages/95/bc/dc386a920942dbdfe480c8a4d953ff77ed3dec99ce736634b6ec4f2d97c1/stevedore-3.3.0.tar.gz  (513kB)
  | Complete output from command python setup.py egg_info:
  | /usr/lib64/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'requires_python'
  | warnings.warn(msg)
  | /usr/lib64/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'long_description_content_type'
  | warnings.warn(msg)
  | /usr/lib64/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'project_urls'
  | warnings.warn(msg)
  | /usr/lib64/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'python_requires'
  | warnings.warn(msg)
  |  
  | Installed /tmp/pip-build-ssyFJl/stevedore/pbr-5.5.1-py2.7.egg
  | Marker evaluation failed, see the following error.  For more information see: http://docs.openstack.org/pbr/latest/user/using.html#environment-markers
  | ERROR:root:Error parsing
  | Traceback (most recent call last):
  | File "/tmp/pip-build-ssyFJl/stevedore/pbr-5.5.1-py2.7.egg/pbr/core.py", line 96, in pbr
  | attrs = util.cfg_to_args(path, dist.script_args)
  | File "/tmp/pip-build-ssyFJl/stevedore/pbr-5.5.1-py2.7.egg/pbr/util.py", line 273, in cfg_to_args
  | kwargs = setup_cfg_to_setup_kwargs(config, script_args)
  | File "/tmp/pip-build-ssyFJl/stevedore/pbr-5.5.1-py2.7.egg/pbr/util.py", line 472, in setup_cfg_to_setup_kwargs
  | if pkg_resources.evaluate_marker('(%s)' % env_marker):
  | File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 1364, in evaluate_marker
  | return interpret(parser.expr(text).totuple(1)[1])
  | File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 1342, in interpret
  | return op(nodelist)
  | File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 1307, in atom
  | return interpret(nodelist[2])
  | File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 1342, in interpret
  | return op(nodelist)
  | File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 1324, in comparison
  | raise SyntaxError(repr(cop)+" operator not allowed in environment markers")
  | SyntaxError: '<' operator not allowed in environment markers
  | error in setup command: Error parsing /tmp/pip-build-ssyFJl/stevedore/setup.cfg: SyntaxError: '<' operator not allowed in environment markers
  |  
  | ----------------------------------------
  | Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-ssyFJl/stevedore/
  | You are using pip version 8.1.2, however version 20.3.1 is available.
  | You should consider upgrading via the 'pip install --upgrade pip' command.
  | Removing intermediate container befb9f9ea6c3
  | error: build error: The command '/bin/sh -c yum -y install epel-release &&     yum -y install jq xmlstarlet patch python-pip &&     yum -y clean all &&     rm -rf /var/cache/yum &&     pip install --upgrade pip six 'python-jenkins==0.4.15' 'jenkins-job-builder==2.0.10' &&     for P in /tmp/patches/*.patch ; do patch --directory / --strip 0 < $P ; done &&     rm -rf /tmp/patches' returned a non-zero code: 1
```

**Comment by Ladicek** [comment]
This project is dead, sorry.
